### ISSUE TITLE
error during loading the clappr rtmp plugin

### ISSUE THREAD

**Issue by chetanbnaik** [clappr/clappr-rtmp-plugin#10]
while loading the plugin in chrome, the rtmp-plugin throws an error as below:

Uncaught Error: Cannot find module 'underscore' clappr.min.js:1a clappr.min.js:1i rtmp.min.js:1(anonymous function) rtmp.min.js:1underscore rtmp.min.js:1i rtmp.min.js:1(anonymous function) rtmp.min.js:1../jst rtmp.min.js:2i rtmp.min.js:1(anonymous function) rtmp.min.js:1./src/main rtmp.min.js:1i rtmp.min.js:1t rtmp.min.js:1(anonymous function) rtmp.min.js:1

**Comment by maxogden** [comment]
I also get this error

**Comment by flavioribeiro** [comment]
@chetanbnaik @maxogden I've fixed on the last release but we need to bump a new version of Clappr to make it work. I'll work on this today and get back to you soon.

**Comment by KCastiglione** [comment]
i also get the error. yes please make it work, doesn't work now.

**Comment by flavioribeiro** [comment]
@chetanbnaik @maxogden @KCastiglione it should be working now. You can find an example [here](http://flv.io/rtmp-plugin.html). Tell me if it works for you.

**Comment by chetanbnaik** [comment]
Yes, it works now... thanks! for fixing it.

**Comment by flavioribeiro** [comment]
awesome! please report if you find any error. :beers:

**Comment by KCastiglione** [comment]
@flavioribeiro it works now, but a new issue https://github.com/clappr/clappr-rtmp-plugin/issues/12
