### ISSUE TITLE
Volume mute

### ISSUE THREAD

**Issue by KCastiglione** [clappr/clappr-rtmp-plugin#13]
Muting volume by tapping speaker doesn't change anything.

**Comment by tarkanlar** [comment]
it changes on me but doesnt show the volume level

**Comment by flavioribeiro** [comment]
sorry for the long delay to answer, are u guys still experiencing this behavior? @KCastiglione @tarkanlar

**Comment by tarkanlar** [comment]
@flavioribeiro working well now. Thanks
