### ISSUE TITLE
Timestamp for live broadcast

### ISSUE THREAD

**Issue by KCastiglione** [clappr/clappr-rtmp-plugin#14]
It will be great to show the timestamp [duration since the broadcast started] for live broadcasts

**Comment by chriswiggins** [comment]
@KCastiglione AFAICT, this isn't available in the RTMP specification, so therefore would have to be supported in the server before anything could be done in Clappr unfortunately

**Comment by flavioribeiro** [comment]
@chriswiggins is right, this information is not available from clappr perspective.
