### ISSUE TITLE
Scaling incorrectly

### ISSUE THREAD

**Issue by kyleparisi** [clappr/clappr-rtmp-plugin#16]
x/post https://github.com/clappr/clappr/issues/446

**Comment by chriswiggins** [comment]
I'm now experiencing this too developing [https://github.com/securogroup/clappr-rtmp-hls](https://github.com/securogroup/clappr-rtmp-hls), and from what I can tell its happening inside RTMP.as

Can someone a bit more familiar with Flash figure out if we should be setting any MediaPlayer/MediaContainer scale stuff? If so, I'm happy to submit a PR

**Comment by chriswiggins** [comment]
I've addressed this in #19 - suggest we close this issue and track it there.
