### ISSUE TITLE
getting error when using `jspm`

### ISSUE THREAD

**Issue by chovy** [clappr/clappr-rtmp-plugin#17]
`Uncaught Error: Cannot find module 'flash'`

I installed it with `jspm install github:clappr/clappr-plugin-rtmp`

and I import it with `import 'clappr/clappr-plugin-rtmp';` which seems to work but the chrome console is saying it can't find `flash`. Mostly likely its `var flash = require('flash')` causing the issue

```
import 'clappr';
import 'clappr/clappr-rtmp-plugin';

```

**Comment by chriswiggins** [comment]
@chovy `flash` is exported through Clappr and the require function gets bundled in with this (and hence its able to resolve `flash`) - does JSPM manipulate the require function?

**Comment by chovy** [comment]
I'm too sure how `jspm` works under the hood. I only recently started using it. But it's becoming quite popular for next generation (es6) apps. This syntax though is the ES6 module loading (`import 'clappr/clappr-rtmp-plugin';`)  that is standard. Babel will transpile it down to ES5.

**Comment by flavioribeiro** [comment]
hey @chovy you can see how we are importing modules [here](https://github.com/clappr/clappr-rtmp-plugin/blob/master/src/main.js#L5). Clappr is exposing the modules [here](https://github.com/clappr/clappr/blob/master/src/main.js). I'll be closing this issue for now, feel free to open it if you think it makes sense.
