### ISSUE TITLE
Add support for Adaptive Streaming

### ISSUE THREAD

**Issue by flavioribeiro** [clappr/clappr-rtmp-plugin#2]
http://refcardz.dzone.com/refcardz/getting-started-web-video

**Comment by sfarges** [comment]
Hello Flávio, do you plan for this plugin to handle rtmp playlist .smil in a near future ?
You know if there is other existing solution for adaptative rtmp in clappr ?
Best regards

**Comment by flavioribeiro** [comment]
Hey @sfarges sorry for the delay to answer. There's some different approaches for adaptive streaming on RTMP so that's why I didn't dive into this yet. Do you want me to help on this?

**Comment by alexandrevicenzi** [comment]
Hi @flavioribeiro,

Does PR #30 solve this issue?

**Comment by flavioribeiro** [comment]
hey @alexandrevicenzi, I think so! I just merged the PR, sorry for the delay. I've added @gfronza as commiter here so he can bump new versions and help us improve this plugin :)

**Comment by flavioribeiro** [comment]
closed by #30

**Comment by alexandrevicenzi** [comment]
@flavioribeiro, that's nice :smile:.
