### ISSUE TITLE
no controls and inifite loader on live rtmp

### ISSUE THREAD

**Issue by maximekrier** [clappr/clappr-rtmp-plugin#21]
When i stream a rtmp live , video and audio works but in the player i have no control and its show a infinite loader : http://i.imgur.com/e9IaAgz.png

**Comment by tarkanlar** [comment]
Hi @maximekrier add ?type=live to your rtmp url
likthis. rtmp://your-url?type=live

**Comment by flavioribeiro** [comment]
@maximekrier the solution that @tarkanlar suggested should fix your problem.
