### ISSUE TITLE
How to use the rtmp-plugin

### ISSUE THREAD

**Issue by lampchop** [clappr/clappr-rtmp-plugin#22]
I am a little confused. I try like this

 <head><script type="text/javascript" src="http://cdn.jsdelivr.net/clappr.rtmp/0.0.6/rtmp.min.js">
</script>
</head>

<body>
  <div id="player"></div>
  <script>
    var player = new Clappr.Player({
        source: "rtmp://xxxx/xxxx.mp4", 
        parentId: "#player",
        plugins: {'playback': [RTMP]}
});
  </script>
But it does not work, should I add   <script type="text/javascript" src="http://cdn.clappr.io/latest/clappr.min.js"></script>
 into this?
Could you give me a example about the full case？
Thank you

**Comment by lampchop** [comment]
![case](https://cloud.githubusercontent.com/assets/12220151/8670024/cc72d4e4-2a4b-11e5-9b1e-0c7d922d1878.jpg)
Should I add this http://cdn.clappr.io/latest/clappr.min.js？

**Comment by towerz** [comment]
@lampchop You are right, you need to add a script tag pointing to clappr itself. The plugins do not include the clappr code.

**Comment by flavioribeiro** [comment]
here's a full working html:

```html
<!DOCTYPE HTML>
<html>
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <script type="text/javascript" charset="utf-8" src="http://cdn.clappr.io/latest/clappr.min.js"></script>
  <script type="text/javascript" charset="utf-8" src="http://cdn.jsdelivr.net/clappr.rtmp/latest/rtmp.min.js"></script>
  <title>HLSJS Test Page</title>
  <script type="text/javascript" charset="utf-8">
window.onload = function() {
  var player = new Clappr.Player({
    source: "rtmp://fms.12E5.edgecastcdn.net/0012E5/mp4:videos/8Juv1MVa-485.mp4",
    parentId: '#player-wrapper',
    plugins: { playback: [RTMP] }
  });
}
  </script>
</head>
<body>
  <div id="player-wrapper">
  </div>
</body>
</html>
```
