### ISSUE TITLE
Uncaught Error: Cannot find module 'flash'

### ISSUE THREAD

**Issue by sc0rp10** [clappr/clappr-rtmp-plugin#25]
Error in *rtmp.min.js*
Browser: Chrome 44
Pepper Flash is disabled (built-in 'click to flash'), but is installed. In other players I see gray block with text "Press Ctrl+Click to enable Flash module", but in this case Clappr with RTMP-module crashes. Native Clappr (w/out RTMP plugin) works fine.

**Comment by cherihung** [comment]
Having same problem. Saw on another issue that this plugin is not compatible with 0.2.x version yet. 
is that the cause for this issue?

**Comment by ebuildy** [comment]
This plugin is broken with latest version of Clappr, try:

    <script type="text/javascript" src="http://cdn.clappr.io/0.1.13/clappr.js"></script>

instead.

**Comment by flavioribeiro** [comment]
hey @ebuildy and @sc0rp10, thanks to @dayvson we have an updated version of the plugin. You can use `http://cdn.jsdelivr.net/clappr.rtmp/latest/rtmp.min.js` to point to the plugin and you'll get `0.0.7` which is compatible with latest clappr!
