### ISSUE TITLE
any plan to upgrade to be compatible with clappr 2.x versions?

### ISSUE THREAD

**Issue by cherihung** [clappr/clappr-rtmp-plugin#26]
is there any plan to update this plugin so it can work with the latest 2.x Clappr?
I'm implementing something that can toggle between rtmp and other supported feeds. so I'd like to just use one version of Clappr instead of having to default back to 1.3.x clappr when toggling to RTMP feeds.

**Comment by flavioribeiro** [comment]
hey @cherihung, thanks to @dayvson we have an updated version of the plugin. You can use `ttp://cdn.jsdelivr.net/clappr.rtmp/latest/rtmp.min.js` to point to the plugin and you'll get `0.0.7` which is compatible with latest clappr!
