### ISSUE TITLE
Be compatible with ClapprLevelSelector

### ISSUE THREAD

**Issue by leandromoreira** [clappr/clappr-rtmp-plugin#33]
We just need to follow https://github.com/clappr/clappr-level-selector-plugin#compatibility

**Comment by gfronza** [comment]
Working on it.

**Comment by gfronza** [comment]
@leandromoreira this implementation is almost done. I'm just waiting a new release of clappr containing the new events (PLAYBACK_LEVEL_SWITCH_START and PLAYBACK_LEVEL_SWITCH_END) and the decision about the https://github.com/clappr/clappr-level-selector-plugin/issues/13.

**Comment by gfronza** [comment]
Done in https://github.com/clappr/clappr-rtmp-plugin/pull/35.
