### ISSUE TITLE
media controls don't work.

### ISSUE THREAD

**Issue by danielim** [clappr/clappr-rtmp-plugin#38]
Following the example on the README, my RTMP video source loads fine with no issues. However the controls don't work. Play button, volume mute, click/drag volume sections, or tracking are affected. Full screen toggle works.

Any idea what could be causing this issue? Thanks.

**Comment by flavioribeiro** [comment]
@danielim are u using latest clappr?

**Comment by danielim** [comment]
I'm using the CDN linked on the README and I believe that's 0.11? I noticed that Clappr has setupSettings instead of updateSettings and wondered if that had anything to do with the issue (it seems Clappr has refactored a bit during the last 2 months).

For some reason I'm having a hard time building clappr-rtmp-plugin with npm run build. Probably an incompatibility with packages on latest node version. Although this is a separate issue, which version of node should be used to build clappr-rtmp-plugin?

**Comment by gfronza** [comment]
@danielim @flavioribeiro I'll look into it.

**Comment by flavioribeiro** [comment]
@gfronza thanks man, I owe you some beers when I go to Brazil! :beers:

**Comment by gfronza** [comment]
@flavioribeiro kkkkkkk :+1:

**Comment by danielim** [comment]
Much appreciated. I'd have tried my hand at it but I haven't figured out which node version I'm supposed to use. Having and "engine" field in package.json would be nice, since a few packages required by this project are depreciated in Node v5.6.0.

Just for archive purposes, the versions that are causing me trouble:
Clappr 0.2.35
clappr-rtmp-plugin 0.11

**Comment by gfronza** [comment]
@danielim There was a problem building this project with the latest clappr version (0.2.35) where babel was updated. I have sent a PR to solve it.

However, I wasn't able to reproduce the problem with media controls you mentioned. All the buttons and the seek bar works fine here.

Check out my entire test.html:

```html
<html>
    <head>
      <script type="text/javascript" src="node_modules/clappr/dist/clappr.js"></script>
      <script type="text/javascript" src="dist/rtmp.min.js"></script>
    </head>

    <body>
      <div id="player"></div>
      <script>
      var player = new Clappr.Player({
          source: "...",
          parentId: "#player",
          plugins: {'playback': [RTMP]},
          rtmpConfig: {
              swfPath: 'dist/assets/RTMP.swf',
              scaling:'stretch',
              playbackType: 'vod',
              bufferTime: 1,
              startLevel: 0,
          },
        });
      </script>
    </body>
</html>
```

**Comment by danielim** [comment]
Hi thanks for looking into it. Unfortunately it still isn't working for me.
http://test.daniel.im/clappr/ is what I'm trying. I have a friend who tried a different RTMP source and said she was getting the same problem.
Here's my src:
`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<div id=player></div>
<script type="text/javascript" src="http://cdn.clappr.io/latest/clappr.min.js"> </script>
<script type="text/javascript" src="http://cdn.jsdelivr.net/clappr.rtmp/latest/rtmp.min.js"></script>


<script> 
var player = new Clappr.Player({ 
        source: "rtmp://184.72.239.149/vod/mp4:BigBuckBunny_115k.mov", 
        plugins: {'playback': [RTMP]}, 
        rtmpConfig: {
            swfPath: './RTMP.swf',
            scaling:'stretch',
            playbackType: 'vod',
            bufferTime: 1,
            startLevel: 0,
            autoSwitch: true
        },
        parentId: "#player" }
    ); 
</script>
</body>
</html>
`
I have also tried without swfPath to no avail.
Sorry for the delay, work has been keeping me busy.

**Comment by danielim** [comment]
ok, managed to get it working. Decided to not use the CDNs and built the dists myself from the git master repo, Clappr outputs a few font files and I included those in the directory, not sure if that was what fixed it or not but at least it works now. Thanks.

clappr-rtmp-plugin now builds with warning that fsevents is not compatible with my arch, but since it's optional I guess I don't have to worry about it.

**Comment by Fiorello** [comment]
Hi, i have the same problem with the latest version of clappr(0.2.90) and clappr-rtmp-plugin(0.0.20), any tips?

Thanks
